/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIMain */

#ifndef _Included_JNIMain
#define _Included_JNIMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIMain
 * Method:    sayHelloToC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIMain_sayHelloToC
  (JNIEnv *, jobject);

/*
 * Class:     JNIMain
 * Method:    average
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_JNIMain_average
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JNIMain
 * Method:    reverse
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIMain_reverse
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JNIMain
 * Method:    median
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_JNIMain_median
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     JNIMain
 * Method:    modifyFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIMain_modifyFields
  (JNIEnv *, jobject);

/*
 * Class:     JNIMain
 * Method:    modifyStaticFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIMain_modifyStaticFields
  (JNIEnv *, jobject);

/*
 * Class:     JNIMain
 * Method:    useCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIMain_useCallback
  (JNIEnv *, jobject);

/*
 * Class:     JNIMain
 * Method:    useStaticCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIMain_useStaticCallback
  (JNIEnv *, jobject);

/*
 * Class:     JNIMain
 * Method:    convertToIntegerObject
 * Signature: (I)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_JNIMain_convertToIntegerObject
  (JNIEnv *, jobject, jint);

/*
 * Class:     JNIMain
 * Method:    convertToDoublePrimitive
 * Signature: (Ljava/lang/Double;)D
 */
JNIEXPORT jdouble JNICALL Java_JNIMain_convertToDoublePrimitive
  (JNIEnv *, jobject, jobject);

/*
 * Class:     JNIMain
 * Method:    getSumAndAverage
 * Signature: ([Ljava/lang/Integer;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_JNIMain_getSumAndAverage
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
